### ISSUE TITLE
Extreme devices vendor:unknown

### ISSUE THREAD

**Issue by manajoe** [netdisco/netdisco-mibs#124]
Hi there,
I don't know if that will be solved by https://github.com/netdisco/netdisco-mibs/issues/118, but I'm having problems with Extreme WiNG devices. All of them are discovered as vendor "unknown" and different models:
![grafik](https://user-images.githubusercontent.com/24794252/93758948-9dc41500-fc09-11ea-8871-4138bc76233b.png)

How can I manage it, that Netdisco recognizes these devices correctly? Or can this be overriden manually somehow?

My setup:
App::Netdisco	2.46.2
SNMP::Info	3.70
DB Schema	63
PostgreSQL	9.6.19
Perl	5.24.1

Best regards
manajoe

**Comment by inphobia** [comment]
well, snmp::info does not yet know about vendor enterprises 388, which is officially known as "symbol":
symbol OBJECT IDENTIFIER ::= { enterprises 388 }

after looking around a bit it seems the related mib is somehow `motorola/WING-MIB.mib`

so i'm afraid that even with updating the mibs the chances of success are pretty slim since afaik snmp::info does not yet have specific support for those devices.

i also had a closer look at your pull request https://github.com/netdisco/netdisco-mibs/pull/119 . while i'm not an extreme product connaisseur , i did notice it touches quite some mibs outside of extreme, like enterasys, xedia, 3com.

i know extreme has been on the warpath lately buying everything they can, so it might be logical that those changes are legit. i'll need some more time to have a closer look at this (since i'm an extreme customer too since they bought aerohive).

for the mib side at least i'll assign this issue to myself.

**Comment by inphobia** [comment]
also #212

**Comment by ollyg** [comment]
I've had an idea to get Netdisco to make educated guesses on enterprise and products unknown OID, here https://github.com/netdisco/netdisco/issues/1109
