### ISSUE TITLE
MIBs for Rittal CMC and Hirschmann

### ISSUE THREAD

**Issue by ArnezuK** [netdisco/netdisco-mibs#62]
Please add this one pleaee

[MIBS.ZIP](https://github.com/netdisco/netdisco-mibs/files/2739761/MIBS.ZIP)
[RITTAL_CMC-III_MIB_V_3_15_20.zip](https://github.com/netdisco/netdisco-mibs/files/2739764/RITTAL_CMC-III_MIB_V_3_15_20.zip)

**Comment by inphobia** [comment]
for hirschmann, are these the most recent mibs? the most recent date i found in them was from 2014, most of them being from before 2010. if they are not the most recent, is there any reason to use these insteaf of the most recent ones?

for rittal, on their site i found https://www.rittal.com/com-en/content/en/support/downloads/Downloads.jsp?category=6&language=1 -> "Software for CMC III / LCP / RiMatrix S" which seems to include the most recent mibs. are these ok or is there are reason to use the older ones you added to this issue?

**Comment by ArnezuK** [comment]
nice to hear someone:
Hirschmann: are the newest MIB's i found in Firmware 9.016
Rittal: maybe newest: http://www.rittal.de/downloads/rimatrix5/security/CMCIII/RITTAL_CMC-III_MIB_V_3_15_20.zip

**Comment by inphobia** [comment]
cool. for rittal i found these ones in the software for their "CMC III Processing Unit DK 7030.000
and the Processing Unit Compact DK 7030.010", will those work for you as well?

[RITTAL_CMC-III_MIB_V_3_15_70.zip](https://github.com/netdisco/netdisco-mibs/files/2821231/RITTAL_CMC-III_MIB_V_3_15_70.zip)

i'll try & get them added, but do be aware that just because the mibs are in the repo you get device support. an snmp::info module is most likely needed too, and i dunno if we add not network devices. 

you can ofcourse use our mib repository for something else (which is totally fine), so i'll try & get them added asap.

**Comment by inphobia** [comment]
#68 for the rittal mibs v 3 15 70

i did have to change 2 defines from snmpCommunityGroup to snmpCommunityTableGroup, since rittal supplies an ancient SNMP-COMMUNITY-MIB since it was also defined in SNMPv2-MIB.

so either use the complete set of netdisco mibs, or the complete set of rittal mibs, but mixing & matching is not supported.

**Comment by inphobia** [comment]
all merged

**Comment by ArnezuK** [comment]
there a some newer mibs for Hirschmann, 2023,
some devices are not shown correctly with the older ones.

inside: Firmwarefile
https://www.belden.com/-/media/project/belden/catalog-assets/assets/2026/02/01/14/44/webmach1000ge09116.zip?rev=862c199d5fcb45c9b05863cd1a935e92
