### ISSUE TITLE
Cumulus Linux, Opengear Console Server, Cisco ME360x, Cisco Cat9K

### ISSUE THREAD

**Issue by avoidingthesubject** [netdisco/netdisco-mibs#89]
Will try add MIBs as attachments in another post

enterprises.40310
OID:1.3.6.1.4.1.40310
Cumulus Networks
Cumulus Linux

cisco - Products.1616
OID:1.3.6.1.4.1.9.1.1616
Cisco ME360x 

cisco - Products.2494
OID:1.3.6.1.4.1.9.1.2494
Cisco CAT9K

enterprises.25049 - enterprises.25049.1.90
OID:1.3.6.1.4.1.25049.1.90
Opengear Console Server

**Comment by inphobia** [comment]
is seems the latest cisco products mib includes the 2494; but the only 2 me360x devices are
```
ciscoMe3600x24fsM               OBJECT IDENTIFIER ::= { ciscoProducts 1250 } -- Cisco ME 3600X Ethernet Access Switch, 24 GE SFP ports + 2 10Gbps/1Gbps SFP+/SFP ports fixed configuration Layer 2/3 Ethernet switch, modular power
ciscoMe3600x24tsM               OBJECT IDENTIFIER ::= { ciscoProducts 1251 } -- Cisco ME 3600X Ethernet Access Switch, 24 10/100/1000 ports + 2 10Gbps/1Gbps SFP+/SFP ports fixed configuration Layer 2/3 Ethernet switch, modular power
```

regretfully i haven't come up with a way yet to add sideload unknown products

**Comment by inphobia** [comment]
a few remarks

- cisco
   .2494 is present in the latest mib, pull request #95 

   for cisco - Products.1616 i would suggest opening a tac case to get it added, if they refuse we will add it manually if you can give us an exact part/model number.

- opengear
   opengear mibs seem to be available publicly at http://ftp.opengear.com/download/snmp/mibs/ , however since i don't use their gear i don't know if we need the legacy or current mibs?
i don't think it matters a lot for us since snmp::info does not have any specific opengear support atm.

- cumulus
   cumulus says you need to download their mibs from your device, but this seems like a list of all their supported mibs with download locations: https://docs.cumulusnetworks.com/cumulus-linux/Monitoring-and-Troubleshooting/Simple-Network-Management-Protocol-SNMP/#supported-mibs . is this link correct & up to date, if so i'll see if i can add them.

**Comment by inphobia** [comment]
note: netdisco-mibs 4.017 has been released with at least products.2494 present. running netdisco-deploy will update them.

for the other changes the comments above are still the relevant.

**Comment by noziwatele** [comment]
Hi, I believe I can respond on this one.

- cisco Products.1616

I have opened a TAC case for 1616 (model number: ME-3600X-24CX-M), it still seems to be missing from the latest MIB file.

- Opengear
The Opengear devices that we use are contained in the 'current' mibs at that FTP location.

- cumulus
Yes, I believe that link is the current location.

- New one: Products.2391
Can I add one more to this request? Cisco Products.2391 (ciscoC9800CLK9). This would be covered by an update to the latest [CISCO-PRODUCTS-MIB](ftp://ftp.cisco.com/pub/mibs/v2/CISCO-PRODUCTS-MIB.my).

Thanks for sorting out the Cisco 2494.

Cheers.

**Comment by inphobia** [comment]
cumulus is waiting in #136 

opengear i still need to look at

i'll try & fit in an update of just cisco-products if time permits

**Comment by inphobia** [comment]
opengear has been added in #154 

i did not however include OGTRAPv2-MIB.mib for 2 reasons:
1) i did not have a timestamp, not a big issue - just annoying
2) it had a notation i haven't yet seen before. i thin it's valid but since this is a trap mib which we'll most likely not use i'll wait until after i release the next mib pack, just to be sure. note the `SNMPv2-MIB::sysName` in there.

```
ogSerialUserNotification TRAP-TYPE
        ENTERPRISE  opengear
        VARIABLES {
                ogAlarmEventId,
                ogAlarmName,
                ogAlarmCheck,
                ogAlarmInstance,
                ogAlarmTime,
                ogAlarmType,
                ogAlarmSummary,
                ogAlarmDevice,
                ogAlarmTriggerValue,
                ogAlarmCurrentValue,
                ogAlarmPreviousValue,
                ogAlarmState,
                SNMPv2-MIB::sysName
        }
        DESCRIPTION
                "The alert sent when a user connection event occurs."
        ::= 3
```

**Comment by inphobia** [comment]
and cisco products updated in #155

**Comment by inphobia** [comment]
i'm moving all missing cisco product id's to #156 while we figure out a solution

**Comment by inphobia** [comment]
and then i think we're done here :)
